version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(levelname)s - %(message)s'
  moderate:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s: %(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file_debug:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/identification_debug.log
    maxBytes: 0
    backupCount: 5
  file:
    class : logging.handlers.RotatingFileHandler
    level: INFO
    formatter: moderate
    filename: logs/identification.log
    maxBytes: 0
    backupCount: 5
root:
  level: DEBUG
  handlers: [file_debug, file, console]